if (!window.BUBU) {
const PRODUCTS = [
  { id: 'p1', img: 'img/p1-cement.png', name: 'Tororo Portland Cement 32.5N, 50kg', cat: 'Building & construction', supplier: 'Kampala Hardware Depot', loc: 'Nakawa, Kampala', price: 33500, unit: 'bag', moq: 50, rating: 4.7, orders: 812, verified: true, mode: 'buy' },
  { id: 'p2', img: 'img/p2-steelbar.png', name: 'Deformed steel bar Y12, 12m length', cat: 'Building & construction', supplier: 'Roofings Distributors Ltd', loc: 'Namanve', price: 62000, unit: 'bar', moq: 25, rating: 4.5, orders: 460, verified: true, mode: 'both' },
  { id: 'p3', img: 'img/p3-maize.png', name: 'Maize grain, grade 1, dried', cat: 'Agriculture & produce', supplier: 'Masindi Grain Union', loc: 'Masindi', price: 1450, unit: 'kg', moq: 1000, rating: 4.8, orders: 1204, verified: true, mode: 'rfq' },
  { id: 'p4', img: 'img/p4-oil.png', name: 'Refined sunflower oil, 20L jerrycan', cat: 'Food & beverage', supplier: 'Lira Oil Millers', loc: 'Lira', price: 138000, unit: 'jerrycan', moq: 10, rating: 4.4, orders: 288, verified: true, mode: 'buy' },
  { id: 'p5', img: 'img/p5-inverter.png', name: 'Solar inverter 3kVA, 24V hybrid', cat: 'Electronics', supplier: 'Sunfield Energy UG', loc: 'Industrial Area, Kampala', price: 1250000, unit: 'unit', moq: 2, rating: 4.6, orders: 96, verified: true, mode: 'both' },
  { id: 'p6', img: 'img/p6-carton.png', name: 'Corrugated shipping cartons, 5-ply', cat: 'Packaging', supplier: 'Nile Packaging Works', loc: 'Jinja', price: 2900, unit: 'carton', moq: 500, rating: 4.2, orders: 331, verified: false, mode: 'rfq' },
  { id: 'p7', img: 'img/p7-gloves.png', name: 'Nitrile examination gloves, box of 100', cat: 'Medical supplies', supplier: 'Medisure Wholesale', loc: 'Ntinda, Kampala', price: 41000, unit: 'box', moq: 20, rating: 4.9, orders: 604, verified: true, mode: 'buy' },
  { id: 'p8', img: 'img/p8-brakepads.png', name: 'Brake pads, Toyota Hiace 5L (set)', cat: 'Auto parts', supplier: 'Kisekka Auto Parts Co.', loc: 'Kisekka Market', price: 78000, unit: 'set', moq: 5, rating: 4.1, orders: 152, verified: false, mode: 'buy' },
  { id: 'p9', img: 'img/p9-caustic.png', name: 'Caustic soda flakes 99%, 25kg', cat: 'Chemicals & industrial', supplier: 'Victoria Chemicals Ltd', loc: 'Kawempe', price: 195000, unit: 'bag', moq: 8, rating: 4.3, orders: 74, verified: true, mode: 'rfq' },
  { id: 'p10', img: 'img/p10-drill.png', name: 'Cordless impact drill 18V + 2 batteries', cat: 'Hardware & tools', supplier: 'Buildmart Tools UG', loc: 'Kikuubo', price: 385000, unit: 'unit', moq: 3, rating: 4.5, orders: 210, verified: true, mode: 'buy' },
  { id:'p11', name:'Face shield, protective isolation', cat:'Medical supplies', price:6800, unit:'unit', moq:100, rating:4.7, orders:214, verified:true, supplier:'Medisure Wholesale', loc:'Ntinda, Kampala' },
  { id:'p12', name:'Medical scrubs set, unisex', cat:'Medical supplies', price:62000, unit:'set', moq:20, rating:4.6, orders:132, verified:true, supplier:'Medisure Wholesale', loc:'Ntinda, Kampala' }
];

const CATEGORIES = [
  ['Building & construction', '18,400 products'],
  ['Agriculture & produce', '9,120 products'],
  ['Food & beverage', '7,640 products'],
  ['Electronics', '6,980 products'],
  ['Hardware & tools', '5,310 products'],
  ['Packaging', '3,870 products'],
  ['Chemicals & industrial', '2,940 products'],
  ['Medical supplies', '2,110 products'],
  ['Auto parts', '4,505 products']
];

const OFFERS = {
  p11: [['Medisure Wholesale Ltd','Ntinda, Kampala',6800,'100 units','+256 772 884 110',true,9],['Joint Medical Store','Nsambya, Kampala',7200,'50 units','+256 758 220 447',true,20],['Eastgate Medical Distributors','Nairobi, Kenya',6400,'500 units','+256 701 447 320',false,3]],
  p12: [['Medisure Wholesale Ltd','Ntinda, Kampala',62000,'20 sets','+256 772 884 110',true,9],['Mbarara Medical Supply','Mbarara',64500,'10 sets','+256 706 553 819',false,4],['Nsambya Uniform Works','Nsambya, Kampala',59800,'40 sets','+256 752 664 209',true,7]],
  p1: [['Kampala Hardware Depot','Nakawa, Kampala',33500,'50 bags','+256 772 415 908',true,6],['Roofings Distributors Ltd','Namanve, Mukono',32800,'100 bags','+256 752 118 340',true,9],['Mbale Builders Supply','Mbale',30800,'200 bags','+256 701 664 219',false,3]],
  p2: [['Roofings Distributors Ltd','Namanve, Mukono',62000,'25 bars','+256 752 118 340',true,9],['Steel & Tube Uganda','Industrial Area, Kampala',60500,'50 bars','+256 772 903 118',true,12],['Kisekka Metal Traders','Kisekka Market',63400,'10 bars','+256 705 220 481',false,4]],
  p3: [['Masindi Grain Union','Masindi',1450,'1,000 kg','+256 774 552 013',true,7],['Kiryandongo Farmers Co-op','Kiryandongo',1390,'5,000 kg','+256 758 441 260',true,5],['Nakasero Produce Dealers','Nakasero, Kampala',1520,'500 kg','+256 700 318 774',false,2]],
  p4: [['Lira Oil Millers','Lira',138000,'10 jerrycans','+256 771 209 663',true,8],['Mukwano Distributors','Industrial Area, Kampala',141500,'20 jerrycans','+256 752 660 900',true,15],['Gulu Wholesale Foods','Gulu',136000,'30 jerrycans','+256 703 887 145',false,3]],
  p5: [['Sunfield Energy UG','Industrial Area, Kampala',1250000,'2 units','+256 776 330 442',true,4],['Solar Now Trading','Ntinda, Kampala',1310000,'1 unit','+256 759 114 806',true,10],['Jinja Power Systems','Jinja',1198000,'5 units','+256 702 445 927',false,2]],
  p6: [['Nile Packaging Works','Jinja',2900,'500 cartons','+256 773 618 250',false,6],['Kampala Carton Mills','Kawempe',2740,'1,000 cartons','+256 751 902 336',true,11],['Riley Packaging Ltd','Namanve',3050,'250 cartons','+256 704 771 528',true,5]],
  p7: [['Medisure Wholesale','Ntinda, Kampala',41000,'20 boxes','+256 772 884 110',true,9],['Joint Medical Store','Nsambya, Kampala',39800,'50 boxes','+256 758 220 447',true,20],['Mbarara Medical Supply','Mbarara',42500,'10 boxes','+256 706 553 819',false,3]],
  p8: [['Kisekka Auto Parts Co.','Kisekka Market',78000,'5 sets','+256 771 445 902',false,7],['Nakawa Motor Spares','Nakawa, Kampala',81000,'3 sets','+256 752 337 664',true,12],['Ndeeba Auto Traders','Ndeeba, Kampala',76500,'10 sets','+256 700 992 158',false,4]],
  p9: [['Victoria Chemicals Ltd','Kawempe, Kampala',195000,'8 bags','+256 774 116 320',true,10],['Uganda Industrial Chem','Industrial Area, Kampala',188000,'20 bags','+256 753 664 209',true,14],['Jinja Chemical Depot','Jinja',201000,'4 bags','+256 705 448 771',false,3]],
  p10: [['Buildmart Tools UG','Kikuubo, Kampala',385000,'3 units','+256 772 552 108',true,6],['Ambitious Tools Centre','Kisekka Market',369000,'6 units','+256 751 880 342',true,8],['Mbarara Tools Centre','Mbarara',392000,'2 units','+256 707 226 903',false,2]]
};

const APPLICANTS = [
  { name: 'Sunfield Energy UG Ltd', role: 'Supplier', loc: 'Industrial Area', waited: '19h',
    sub: 'Applied 14 Aug · Electronics · 3 listings pending publication',
    records: [['URSB number','80020002884411 · matched', true],['URA TIN','1004472281 · active', true],['VAT registration','Not registered', true],['Trading licence','Expired 30 June 2026', false],['Director NIN','CF88031122KLB · matched', true],['Payout account','Centenary Bank ·3901…2288', true]],
    files: ['Certificate of incorporation.pdf','URA TIN certificate.pdf','Trading licence 2025.pdf','Director national ID.jpg'] },
  { name: 'Mbale Builders Supply', role: 'Supplier', loc: 'Mbale', waited: '14h',
    sub: 'Applied 14 Aug · Building materials · 11 listings pending publication',
    records: [['URSB number','80019887440021 · matched', true],['URA TIN','1003318802 · active', true],['VAT registration','1003318802-V · active', true],['Trading licence','Mbale MC, valid to 31 Dec 2026', true],['Director NIN','CM77041290PQ7L · matched', true],['Payout account','MTN MoMo +256 701 664 219', true]],
    files: ['Certificate of incorporation.pdf','URA TIN certificate.pdf','Trading licence 2026.pdf','VAT certificate.pdf','Director national ID.jpg'] },
  { name: 'Kyanja Builders Ltd', role: 'Buyer', loc: 'Kampala', waited: '9h',
    sub: 'Applied 15 Aug · Buyer account · credit terms requested',
    records: [['URSB number','80021144902288 · no match found', false],['URA TIN','1005520147 · active', true],['VAT registration','Not registered', true],['Trading licence','KCCA, valid to 31 Dec 2026', true],['Director NIN','CM82119043TR6M · matched', true],['Payout account','Not required for buyers', true]],
    files: ['URA TIN certificate.pdf','Trading licence 2026.pdf','Director national ID.jpg'] },
  { name: 'Masindi Grain Union', role: 'Supplier', loc: 'Masindi', waited: '6h',
    sub: 'Applied 15 Aug · Agriculture and produce · 6 listings pending publication',
    records: [['URSB number','80017762210094 · matched', true],['URA TIN','1002204118 · returns overdue', false],['VAT registration','Not registered', true],['Trading licence','Masindi DLG, valid to 31 Dec 2026', true],['Director NIN','CF91072255GH3D · matched', true],['Payout account','Stanbic Bank ·9014…7731', true]],
    files: ['Cooperative registration.pdf','Trading licence 2026.pdf','Chairperson national ID.jpg'] }
];

const MODALS = {
  addProduct: { title: 'Add a product', sub: 'Buyers search by specification, so fill what you can now and refine later.',
    fields: [['Product name','Tororo Portland Cement 32.5N, 50kg bag',''],['Category','Building materials > Cement',''],['Price per unit','33,500','UGX'],['Minimum order','50','bags'],['Lead time','2','days']],
    note: 'Products go live once your trading licence is current.', primary: 'Save and publish', secondary: 'Save as draft' },
  quickAdd: { title: 'Quick add', sub: 'Paste a list and BUBU will create one product per line.',
    fields: [['Paste product lines','Cement 32.5N 50kg, 33500, per bag','']],
    note: 'Nine of ten quick-added products still need a photo before they rank in search.', primary: 'Create products', secondary: 'Cancel' },
  uploadPhotos: { title: 'Upload photos', sub: 'Clear photos on a plain background earn roughly three times more enquiries.',
    fields: [['Attach files','Choose from device',''],['Photo type','Product photo','']],
    note: 'JPG or PNG, up to 5 MB each. Review takes about 4 hours.', primary: 'Upload', secondary: 'Cancel' },
  uploadDoc: { title: 'Upload document', sub: 'Records are checked against URSB, URA and NIRA before your badge updates.',
    fields: [['Document type','VAT registration certificate',''],['Reference number','',''],['Attach file','Choose from device','']],
    note: 'Copies are retained under the Data Protection and Privacy Act, 2019.', primary: 'Submit for verification', secondary: 'Cancel' },
  renew: { title: 'Renew gold supplier', sub: 'Your listing expires on 31 August 2026.',
    fields: [['Plan','Gold supplier, 12 months',''],['Amount','1,200,000','UGX'],['Pay with','MTN MoMo +256 772 415 908','']],
    note: 'An OTP will be sent to the paying number to authorise the debit.', primary: 'Send payment request', secondary: 'Choose another plan' },
  contactBuyer: { title: 'Contact buyer', sub: 'Two lead credits will be used. You have 11 remaining.',
    fields: [['Buyer','Nakawa Trading Co. Ltd',''],['Your price','33,500','UGX per bag'],['Quantity you can supply','500','bags'],['Message','We can deliver 500 bags to Ntinda within 48 hours.','']],
    note: 'The buyer sees your verified number and can call you back directly.', primary: 'Send quote and reveal number', secondary: 'Cancel' },
  callBuyer: { title: 'Call through BUBU', sub: 'Your private line stays hidden. The buyer sees 0800 218 400.',
    fields: [['Buyer','Grace Nakato, Nakawa Trading Co. Ltd',''],['Call from','+256 772 415 908, primary handset','']],
    note: 'Calls are recorded for dispute resolution and kept for 90 days.', primary: 'Place call', secondary: 'Cancel' },
  labelChat: { title: 'Label this chat', sub: 'Labels drive your lead manager filters and follow-up reminders.',
    fields: [['Label','Hot lead',''],['Follow up on','18 August 2026',''],['Note','Wants palletised delivery, offloading required.','']],
    note: '', primary: 'Save label', secondary: 'Cancel' },
  shareProduct: { title: 'Share product', sub: 'Send the buyer a direct link to this listing.',
    fields: [['Link','bubu.market/kampala-hardware-depot/cement-32-5n',''],['Send via','WhatsApp','']],
    note: '', primary: 'Copy link', secondary: 'Close' },
  preview: { title: 'Buyer preview', sub: 'This is how the listing appears in search results.',
    fields: [['Shown as','Tororo Portland Cement 32.5N, 50kg bag',''],['Price shown','UGX 33,500 per bag',''],['Badge','URSB verified','']],
    note: 'Adding the five missing specifications would raise this listing from position 7 to about position 3.', primary: 'Close preview', secondary: '' },
  addToCatalog: { title: 'Add to your catalog', sub: 'Selected products are created with the category and specification template filled in.',
    fields: [['Products selected','MS pipe 2in, GI angle 40×40',''],['Price basis','Set later','']],
    note: 'Buy lead alerts for these categories start the moment the products go live.', primary: 'Add 2 products', secondary: 'Cancel' },
  editProfile: { title: 'Edit business details', sub: 'Changes to registration numbers are re-verified before the badge returns.',
    fields: [['URSB registration number','80020003456789',''],['URA TIN','1002938475',''],['Trading licence','KCCA/TL/2026/44120','']],
    note: 'Verification usually completes within one working day.', primary: 'Save changes', secondary: 'Cancel' },
  tender: { title: 'Tender details', sub: 'Submissions are made on the procuring body\u2019s portal. BUBU tracks the deadline for you.',
    fields: [['Reference','MoES/SUPPLIES/2026-27/0041',''],['Estimated value','UGX 340,000,000',''],['Closes','28 August 2026, 3:00 pm',''],['Bid security','2% of bid value','']],
    note: 'Required documents: URSB certificate, URA tax clearance, trading licence, two references.', primary: 'Download tender pack', secondary: 'Add reminder' },
  editProduct: { title: 'Edit product', sub: 'Changes appear in search within a few minutes.',
    fields: [['Product name','Tororo Portland Cement 32.5N, 50kg bag',''],['Price per unit','33,500','UGX'],['Minimum order','50','bags']],
    note: '', primary: 'Save changes', secondary: 'Cancel' },
  addSpec: { title: 'Add specification', sub: 'Listings with a complete specification rank higher and attract better leads.',
    fields: [['Specification','Brand',''],['Value','Tororo Cement','']],
    note: 'Each completed specification raises the quality score by about 8 points.', primary: 'Save specification', secondary: 'Cancel' },
  addVideo: { title: 'Add a video', sub: 'A short clip of the product in your yard converts better than studio shots.',
    fields: [['Attach file','Choose from device',''],['Duration limit','60 seconds','']],
    note: 'MP4 up to 40 MB. Review takes about 4 hours.', primary: 'Upload video', secondary: 'Cancel' },
  viewPdf: { title: 'Product datasheet', sub: 'Shared with buyers who request full specifications.',
    fields: [['File','cement-32-5n-datasheet.pdf',''],['Size','680 KB',''],['Updated','06 May 2026','']],
    note: '', primary: 'Download', secondary: 'Replace file' },
  productMenu: { title: 'Product options', sub: 'Applies to this listing only.',
    fields: [['Move to','Inactive products',''],['Duplicate as','New listing in the same group',''],['Delete','Permanently remove this listing','']],
    note: 'Deleting a product also removes its enquiry history.', primary: 'Apply', secondary: 'Cancel' },
  photoViewer: { title: 'Photo', sub: 'Cement 50kg bag, stacked · product photo.',
    fields: [['Uploaded','14 Aug 2026',''],['Status','Approved',''],['Used on','3 listings','']],
    note: '', primary: 'Set as main photo', secondary: 'Delete photo' },
  addPhoto: { title: 'Add photo', sub: 'Plain background, daylight, one product per frame.',
    fields: [['Attach files','Choose from device',''],['Photo type','Product photo','']],
    note: 'JPG or PNG, up to 5 MB each.', primary: 'Upload', secondary: 'Cancel' },
  invoices: { title: 'Past invoices', sub: 'Receipts for your BUBU services.',
    fields: [['Gold supplier 2025-26','UGX 1,200,000 · paid 01 Sep 2025',''],['Buy lead credits','UGX 480,000 · paid 01 Sep 2025',''],['Storefront banner','UGX 300,000 · paid 01 Jun 2026','']],
    note: '', primary: 'Download all', secondary: 'Close' },
  account: { title: 'Moses Kagimu', sub: 'Kampala Hardware Depot Ltd · gold supplier.',
    fields: [['Switch role','Buyer or admin view',''],['Staff logins','2 active',''],['Sign out','End this session','']],
    note: '', primary: 'Close', secondary: '' },
  postReq: { title: 'Post your requirement', sub: 'Verified suppliers in the category reply with quotes, usually within 3 hours.',
    fields: [['Product or service','Tororo Portland Cement 32.5N',''],['Quantity','500','bags'],['Deliver to','Ntinda, Kampala',''],['Needed by','12 September 2026',''],['Budget per unit','33,000','UGX']],
    note: 'Your phone number is shared only with suppliers who quote. An OTP confirms the request.', primary: 'Submit requirement', secondary: 'Cancel' },
  verify: { title: 'Supplier verification report', sub: 'Kampala Hardware Depot Ltd, checked 15 August 2026.',
    fields: [['URSB registration','80020003456789 · active',''],['URA TIN','1002938475 · tax compliant',''],['Trading licence','KCCA, valid to 31 December 2026',''],['BUBU history','62 orders · 4.6 rating · no open disputes',''],['Payment protection','Covered','']],
    note: 'This report reflects records held on 15 August 2026 and does not guarantee performance.', primary: 'Download report', secondary: 'Close' },
  protect: { title: 'How payment protection works', sub: 'Escrow held by BUBU on every protected order.',
    fields: [['Funding','MTN MoMo, Airtel Money or bank transfer',''],['Held by','BUBU escrow account, Stanbic Bank Uganda',''],['Release','On your confirmation, or 7 days after delivery',''],['Fee','1.5% of order value, paid by the supplier','']],
    note: 'Disputes are reviewed within two working days. Funds stay held until resolved.', primary: 'Enable on my orders', secondary: 'Close' },
  service: { title: 'Request this service', sub: 'Three vetted providers will contact you.',
    fields: [['Service','Accounting software',''],['Business size','6 to 20 staff',''],['Preferred district','Kampala','']],
    note: 'Providers are independent businesses. BUBU does not resell their services.', primary: 'Request quotes', secondary: 'Cancel' },
  feedback: { title: 'Rate this supplier', sub: 'Ratings are shown on the supplier storefront.',
    fields: [['Supplier','@COMPANY@',''],['Rating','5 of 5',''],['What went well','Delivered on time and the grade matched.','']],
    note: '', primary: 'Submit rating', secondary: 'Cancel' },
  contactSupplier: { title: 'Send a message', sub: 'The supplier replies in your lead inbox and by SMS.',
    fields: [['Supplier','@COMPANY@',''],['Requirement','Tororo cement 32.5N, 500 bags',''],['Message','Can you hold this price until Friday?','']],
    note: '', primary: 'Send message', secondary: 'Cancel' },
  ship: { title: 'Find transporters', sub: 'Nine hauliers cover this route.',
    fields: [['Route','Kampala to Mbarara',''],['Load','Full truck, 9 to 18 tonnes',''],['Indicative rate','UGX 1,150,000 – 1,480,000',''],['Transit','1 day','']],
    note: 'Rates exclude offloading and are confirmed by the transporter before booking.', primary: 'Request bookings', secondary: 'Cancel' },
  finance: { title: 'Check eligibility', sub: 'A soft check that does not affect your credit record.',
    fields: [['Facility','Invoice discounting',''],['Trading history','14 months on BUBU',''],['Indicative limit','UGX 42,000,000',''],['Lender','Stanbic Bank Uganda','']],
    note: 'Final terms are set by the lender after full assessment.', primary: 'Send my details', secondary: 'Cancel' },
  upgrade: { title: 'Confirm your upgrade', sub: 'Business plan, billed to your chosen method.',
    fields: [['Plan','Business',''],['Amount','180,000','UGX per month'],['Pay with','MTN MoMo +256 772 903 445',''],['Starts','Immediately, prorated','']],
    note: 'An OTP will be sent to the paying number. Cancel any time before the next billing date.', primary: 'Send payment request', secondary: 'Cancel' },
  changeAddress: { title: 'Delivery address', sub: 'Choose where this order should be delivered.',
    fields: [['Head office and main store','Plot 12, Ntinda Industrial Area, Kampala',''],['Kyanja site store','Kyanja Ring Road, Wakiso',''],['Mukono depot','Seeta, Mukono municipality','']],
    note: 'Receiving hours and offloading equipment are shown to the transporter.', primary: 'Use this address', secondary: 'Cancel' },
  placeOrder: { title: 'Place order', sub: 'Funds are held in BUBU escrow until you confirm delivery.',
    fields: [['Order value','16,750,000','UGX'],['Escrow fee','Paid by the supplier',''],['Pay with','MTN MoMo +256 772 903 445',''],['Delivery','Ntinda, within 48 hours','']],
    note: 'An OTP will be sent to authorise the debit.', primary: 'Confirm and pay', secondary: 'Cancel' },
  requestQuote: { title: 'Request a quote', sub: 'Sent to every verified supplier of this product.',
    fields: [['Product','Tororo Portland Cement 32.5N',''],['Quantity','500','bags'],['Deliver to','Ntinda, Kampala',''],['Needed by','12 September 2026','']],
    note: 'Suppliers see your company name, not your phone number, until you accept a quote.', primary: 'Send request', secondary: 'Cancel' },
  acceptQuote: { title: 'Accept this quote', sub: 'Creates an escrow-protected order.',
    fields: [['Supplier','@COMPANY@',''],['Price','33,500','UGX per bag'],['Total','16,750,000','UGX'],['Delivery','48 hours from payment','']],
    note: 'The supplier is paid only after you confirm delivery.', primary: 'Accept and fund escrow', secondary: 'Cancel' },
  dispute: { title: 'Dispute BM-2026-0392', sub: 'Roofings Distributors Ltd vs Mukono Works Ltd.',
    fields: [['Raised','11 August 2026 by the buyer',''],['Claim','120 sheets short on a 900 sheet order',''],['Order value','43,650,000','UGX'],['Escrow held','43,650,000','UGX'],['Evidence','Delivery note, 4 photos, weighbridge ticket','']],
    note: 'Releasing partially settles the supplier and refunds the balance to the buyer the same day.', primary: 'Release 84% and refund balance', secondary: 'Request more evidence' },
  escrowRelease: { title: 'Release escrow', sub: 'Funds move to the supplier payout account.',
    fields: [['Order','BM-2026-0418',''],['Amount','16,750,000','UGX'],['To','Kampala Hardware Depot Ltd, Stanbic 4417',''],['Platform fee','251,250','UGX']],
    note: 'Two admin approvals are required above UGX 20,000,000.', primary: 'Approve release', secondary: 'Cancel' },
  editCategory: { title: 'Edit category', sub: 'Category rules drive search, lead routing and fees.',
    fields: [['Category','Building and construction materials',''],['Parent','None, top level',''],['Commission','1.5','%'],['Requires certificate','UNBS product certificate','']],
    note: 'Changes apply to new listings immediately and to existing listings overnight.', primary: 'Save category', secondary: 'Cancel' },
  editFee: { title: 'Edit fee rule', sub: 'Applies to every order matching the conditions.',
    fields: [['Rule','Standard escrow commission',''],['Rate','1.5','% of order value'],['Charged to','Supplier',''],['Minimum','5,000','UGX']],
    note: 'Fee changes require finance sign-off before they take effect.', primary: 'Submit for sign-off', secondary: 'Cancel' },
  adminMember: { title: 'Member record', sub: 'Nakawa Trading Co. Ltd, buyer since March 2024.',
    fields: [['URSB','80014422019876 · matched',''],['URA TIN','1002938475 · compliant',''],['Orders','41 completed, 1 refunded',''],['Standing','Good','']],
    note: '', primary: 'Close', secondary: 'Suspend account' },
  searchScope: { title: 'Search scope', sub: 'Choose what the search bar looks through.',
    fields: [['Buy leads','Buyer requirements in your categories',''],['My products','Your own catalog',''],['Suppliers','Other businesses on BUBU','']],
    note: '', primary: 'Apply', secondary: 'Cancel' },
  otp: { title: 'Confirm with OTP', sub: 'We sent a six digit code to +256 772 415 908.',
    fields: [['Enter code','• • •   • • •','']],
    note: 'The code expires in 4 minutes 30 seconds. Resend available after 60 seconds.', primary: 'Confirm', secondary: 'Resend code' }
};

const NOTIF = [
  ['group','Enquiries'],
  ['enquiries','Business enquiries','Sent to you by buyers through BUBU.','lock','na','on','on'],
  ['replies','Replies to your quotes','When a buyer answers a quote you have sent.','on','na','on','off'],
  ['followups','Follow-up reminders','Ten minutes before an upcoming reminder is due.','on','na','on','off'],
  ['missedpns','Missed BUBU number calls','Buyer name, town and requirement when you miss a call on 0800 218 400.','off','off','on','na'],
  ['answeredpns','Answered BUBU number calls','Buyer details, and which handset answered the call.','off','na','on','na'],
  ['group','Buy leads and tenders'],
  ['leadalerts','Buy lead alerts','New buyer requirements posted between 7am and 9pm.','on','on','on','off'],
  ['nightleads','Night buy lead alerts','Requirements posted between 9pm and midnight.','na','na','off','na'],
  ['leadpurchase','Buy lead purchase receipts','Buyer contact details for every lead credit you spend.','off','na','on','na'],
  ['leadcredits','Credit allocation and lapse','How your monthly lead credits are allocated and when they expire.','on','na','na','na'],
  ['tenders','Tender alerts','Government, NGO and district tenders in your categories.','on','na','on','off'],
  ['tenderpurchase','Tender purchase receipts','Tender packs you have bought through BUBU.','on','na','na','na'],
  ['group','Orders and money'],
  ['payouts','Payout and escrow alerts','Escrow funding, release and bank settlement.','on','on','on','on'],
  ['disputes','Disputes and claims','When a buyer raises a claim on one of your orders.','lock','on','on','on'],
  ['licence','Licence and document expiry','Thirty days before a trading licence or certificate lapses.','on','on','on','na'],
  ['group','Promotional communication'],
  ['offers','BUBU new services','Newly launched services that could grow your business.','lock','on','na','na'],
  ['thirdparty','Partner offers','Offers from banks, insurers and logistics partners on BUBU.','off','off','na','na'],
  ['surveys','Business surveys','Market research run by independent third parties.','on','na','na','na'],
  ['group','Service messages'],
  ['service','BUBU service messages','Messages about your active services and gold supplier listing.','lock','on','na','na'],
  ['group','Your buying activity'],
  ['buying','Buying reminders','Products you have viewed as a buyer and may want to reorder.','on','na','na','na'],
  ['wacomms','WhatsApp confirmations','Confirmation alerts for requirements you post as a buyer.','na','na','na','on']
];

const PNS_FAQ = [
  ['What is the BUBU number?','It is a single 0800 line printed on your storefront and quotes. Buyers dial it and BUBU connects them to your handsets without revealing your private line.'],
  ['What do I gain from it?','Every call is logged against a buyer record, so a missed call still arrives as a lead with the buyer name, town and requirement. Your personal number stays private.'],
  ['In what order are my numbers rung?','In the order listed, ten to twenty seconds each, unless you choose to ring all handsets at once in Call handling.'],
  ['What counts as office and after hours?','Office hours are 8am to 6pm Monday to Saturday. After hours covers 6pm to 8am, Sundays and public holidays. Each handset can be set separately for both.'],
  ['How many numbers can I link?','Up to five, mobile or landline, each verified once by SMS code.'],
  ['Where do buyers see the number?','On your storefront, on every product listing, in quotes you send and in search results.'],
  ['What happens if I miss a call?','BUBU sends an SMS and an app alert with the buyer details, and the call appears in the lead manager so you can call back through the same line.'],
  ['Whose number shows on my caller ID?','You see 0800 218 400, not the buyer number, so save it in your contacts as BUBU Buyer.'],
  ['Can I print it on my stationery?','Yes. The number stays with your account for as long as your listing is active.'],
  ['Are calls recorded?','Yes, for dispute resolution. Recordings are kept for 90 days under the Data Protection and Privacy Act, 2019.']
];

const ACCOUNTS = [
  { role:'Supplier', id:'772 415 908', pass:'trade2026', first:'Moses', person:'Moses Kagimu', roleTitle:'Director',
    initials:'KH', company:'Kampala Hardware Depot Limited', trade:'KH Depot', meta:'Gold supplier · Nakawa',
    email:'moses@khd.co.ug', alt:'+256 752 118 340', addr:'Plot 44, Sixth Street, Industrial Area', district:'Kampala',
    tin:'1002938475', ursb:'80020003456789', licence:'KCCA/TL/2026/44120', type:'Wholesaler', since:'11 March 2019',
    cats:['Building & construction','Hardware & tools'],
    about:'Wholesale distributor of cement, steel reinforcement, roofing and hardware across central Uganda. Stockist for Tororo Cement, Roofings Group and Steel and Tube.',
    coverage:'Kampala, Wakiso, Mukono · 6 trucks, 3 to 10 tonne',
    nature:'Wholesale of cement, steel reinforcement, roofing and hardware',
    staffCount:'34 permanent, 12 casual', turnover:'UGX 6.2bn, financial year 2025', warehouse:'2,400 square metres under roof',
    fleet:'6 trucks, 3 to 10 tonne, own drivers', brands:'Tororo Cement, Roofings Group, Steel and Tube, Bosch',
    lines:[['Tororo Portland Cement 32.5N, 50kg','UGX 33,500 / bag','p1-cement'],['Deformed steel bar Y12, 12m','UGX 62,000 / bar','p2-steelbar'],['Roofing sheets 30g, pre-painted','UGX 48,500 / sheet','x-roofing'],['Cordless impact drill 18V','UGX 385,000 / unit','p10-drill'],['Binding wire 16g','UGX 9,200 / kg','x-wire'],['Hollow section 50×50','UGX 78,000 / length','x-hollow'],['Y10 steel bar, 12m','UGX 44,000 / bar','x-y10'],['Concrete nails 4in','UGX 8,400 / kg','x-nails']] },

  { role:'Supplier', id:'772 660 214', pass:'tools2026', first:'Sarah', person:'Sarah Nabirye', roleTitle:'Managing partner',
    initials:'KT', company:'Kisekka Tools and Hardware Limited', trade:'Kisekka Tools', meta:'Silver supplier · Kisekka',
    email:'sarah@kisekkatools.co.ug', alt:'+256 703 118 442', addr:'Shop 118, Kisekka Market, Kampala', district:'Kampala',
    tin:'1004471902', ursb:'80020006611024', licence:'KCCA/TL/2026/51188', type:'Retailer and wholesaler', since:'04 July 2016',
    cats:['Hardware & tools','Electronics'],
    about:'Power tools, hand tools and fasteners for contractors and workshops. Authorised service point for Bosch and Total Tools in Kisekka Market.',
    coverage:'Kampala, Wakiso, Jinja, Mbarara · courier and bus parcel',
    nature:'Retail and wholesale of power tools, hand tools and fasteners',
    staffCount:'11 permanent, 4 casual', turnover:'UGX 1.9bn, financial year 2025', warehouse:'480 square metres, two shops',
    fleet:'2 vans, courier partners upcountry', brands:'Bosch, Total Tools, Ingco, Stanley',
    lines:[['Cordless impact drill 18V, two batteries','UGX 385,000 / unit','t-drill'],['Angle grinder 900W','UGX 185,000 / unit','t-grinder'],['Concrete nails 4in','UGX 8,400 / kg','x-nails'],['Binding wire 16g','UGX 9,200 / kg','x-wire'],['Steel wheelbarrow, heavy duty','UGX 168,000 / unit','x-wheelbarrow'],['Drill bit set, 19 pieces','UGX 46,000 / set','t-drillbits'],['Hollow section 50×50','UGX 78,000 / length','x-hollow'],['Solar inverter 3kVA hybrid','UGX 1,250,000 / unit','p5-inverter']] },

  { role:'Supplier', id:'774 552 013', pass:'harvest2026', first:'Denis', person:'Denis Okot', roleTitle:'General manager',
    initials:'NG', company:'Nile Grain and Produce Limited', trade:'Nile Grain', meta:'Gold supplier · Lira',
    email:'denis@nilegrain.co.ug', alt:'+256 758 441 260', addr:'Plot 9, Aputi Road, Lira Industrial Area', district:'Lira',
    tin:'1003882140', ursb:'80020004417755', licence:'LMC/TL/2026/00921', type:'Aggregator and processor', since:'22 January 2018',
    cats:['Agriculture','Packaging'],
    about:'Aggregator of maize, beans, sesame and sunflower from northern Uganda. UNBS certified drying and grading, warehouse receipts issued on delivery.',
    coverage:'Lira, Gulu, Kiryandongo, Masindi, Kampala · 9 trucks',
    nature:'Aggregation, drying, grading and wholesale of cereals and oilseeds',
    staffCount:'26 permanent, 60 seasonal', turnover:'UGX 4.4bn, financial year 2025', warehouse:'3,100 square metres, 4,000 tonne capacity',
    fleet:'9 trucks, 5 to 28 tonne', brands:'Own brand, contracted to WFP and Aponye',
    lines:[['White maize grain, grade 1','UGX 1,450 / kg','a-maize-grain'],['Refined sunflower oil, 20L jerrycan','UGX 138,000 / jerrycan','p4-oil'],['Sesame seed, hulled','UGX 5,900 / kg','a-sesame-hulled'],['Beans, yellow long','UGX 3,700 / kg','a-beans-yellow'],['Maize bran, animal feed','UGX 780 / kg','a-maize-bran'],['Robusta coffee, screen 15','UGX 9,800 / kg','a-coffee-robusta'],['Woven polypropylene bags, 100kg','UGX 1,250 / bag','a-woven-bag'],['Groundnuts, red beauty','UGX 6,400 / kg','a-groundnuts']] },

  { role:'Supplier', id:'776 812 340', pass:'concrete2026', first:'Peter', person:'Peter Ssemakula', roleTitle:'Operations director',
    initials:'NC', company:'Namanve Construction Supplies Limited', trade:'Namanve Construction', meta:'Gold supplier · Namanve',
    email:'peter@namanveconstruction.co.ug', alt:'+256 752 907 118', addr:'Plot 210, Namanve Industrial Park, Mukono', district:'Mukono',
    tin:'1007244810', ursb:'80020008841207', licence:'MMC/TL/2026/01184', type:'Construction materials supplier', since:'09 May 2015',
    cats:['Building & construction','Packaging'],
    about:'Aggregates, ready-mix concrete, blocks and formwork for contractors in Kampala, Wakiso and Mukono. Own quarry at Kasenge and a batching plant at Namanve.',
    coverage:'Kampala, Wakiso, Mukono, Jinja · 14 tippers and 4 mixers',
    nature:'Quarrying, ready-mix concrete production and supply of construction materials',
    staffCount:'62 permanent, 40 casual', turnover:'UGX 11.8bn, financial year 2025', warehouse:'Quarry 12 acres, batching plant 60m³ per hour',
    fleet:'14 tippers, 4 concrete mixers, 2 boom pumps', brands:'Own quarry output, Tororo Cement, Roofings Group',
    lines:[['Ready-mix concrete C25','UGX 465,000 / m³','p1-cement'],['Aggregate 3/4 inch, crushed stone','UGX 78,000 / tonne','c-aggregate'],['Lake sand, washed','UGX 62,000 / tonne','c-sand'],['Hardcore, quarry run','UGX 48,000 / tonne','c-hardcore'],['Solid concrete block 9 inch','UGX 4,300 / block','c-block'],['Tororo Portland Cement 32.5N, 50kg','UGX 32,800 / bag','p1-cement'],['Steel formwork panel, 1200×600','UGX 210,000 / panel','c-formwork'],['Damp proof course, 1m roll','UGX 34,000 / roll','c-dpc']] },

  { role:'Supplier', id:'772 884 110', pass:'medic2026', first:'Aisha', person:'Aisha Nakiwala', roleTitle:'Pharmacy director',
    initials:'MS', company:'Medisure Wholesale Limited', trade:'Medisure Wholesale', meta:'Gold supplier · Ntinda',
    email:'aisha@medisure.co.ug', alt:'+256 758 220 447', addr:'Plot 7, Kigowa Road, Ntinda', district:'Kampala',
    tin:'1009446721', ursb:'80020011552308', licence:'NDA/WHS/2026/00612', type:'Medical wholesaler', since:'18 August 2017',
    cats:['Medical supplies','Packaging'],
    about:'Wholesale of examination gloves, protective equipment and clinical consumables to hospitals, clinics and NGOs. NDA licensed and stocked from Ntinda.',
    coverage:'Nationwide · courier to all regional referral hospitals',
    nature:'Wholesale of medical and protective equipment',
    staffCount:'19 permanent, 6 casual', turnover:'UGX 5.1bn, financial year 2025', warehouse:'900 square metres, temperature logged',
    fleet:'3 vans, cold box capable', brands:'Medisure own brand, Hartmann, Ansell',
    lines:[['Nitrile examination gloves, box of 100','UGX 41,000 / box','p7-gloves'],['Face shield, protective isolation','UGX 6,800 / unit','m-faceshield'],['Medical scrubs set, unisex','UGX 62,000 / set','m-scrubs'],['Surgical masks 3-ply, box of 50','UGX 12,400 / box','p7-gloves'],['Corrugated shipping cartons, 5-ply','UGX 2,900 / carton','p6-carton'],['Caustic soda flakes, 25kg','UGX 195,000 / bag','p9-caustic']] },

  { role:'Buyer', id:'772 903 445', pass:'build2026', first:'Grace', person:'Grace Nakato', roleTitle:'Procurement lead',
    initials:'NT', company:'Nakawa Trading Co. Ltd', trade:'Nakawa Trading', meta:'Buyer · TIN 1002938475',
    email:'grace@nakawatrading.co.ug', alt:'+256 752 118 077', addr:'Plot 12, Ntinda Industrial Area, Nakawa Division', district:'Kampala',
    tin:'1002938475', ursb:'80014422019876', licence:'KCCA/TL/2026/33017', type:'Contractor', since:'March 2024',
    cats:['Building & construction','Hardware & tools'],
    buys:'Cement, steel bar, roofing sheets, formwork',
    spend:'UGX 214m', suppliers:'17',
    orders:[['BM-2026-0418','Tororo cement 32.5N × 500 bags','Kampala Hardware Depot','UGX 16,750,000','03 Aug 2026','Delivered'],['BM-2026-0392','Roofing sheets 30g × 900','Roofings Distributors Ltd','UGX 43,650,000','21 Jul 2026','Delivered'],['BM-2026-0355','Steel bar Y12 × 120','Steel & Tube Uganda','UGX 7,440,000','02 Jul 2026','Delivered'],['BM-2026-0331','Impact drill 18V × 12','Buildmart Tools UG','UGX 4,620,000','14 Jun 2026','Refunded']] },

  { role:'Buyer', id:'752 664 209', pass:'clinic2026', first:'Peter', person:'Peter Wasswa', roleTitle:'Procurement officer',
    initials:'NH', company:'Nsambya Hospital Supplies Limited', trade:'Nsambya Hospital', meta:'Buyer · TIN 1010773204',
    email:'peter@nsambyasupplies.co.ug', alt:'+256 701 992 118', addr:'Nsambya Hill, Makindye Division', district:'Kampala',
    tin:'1010773204', ursb:'80020012288417', licence:'KCCA/TL/2026/61204', type:'Hospital group', since:'January 2020',
    cats:['Medical supplies','Packaging'],
    buys:'Examination gloves, protective equipment, scrubs, masks',
    spend:'UGX 812m', suppliers:'19',
    orders:[['BM-2026-0540','Nitrile gloves × 4,000 boxes','Medisure Wholesale','UGX 164,000,000','14 Aug 2026','Delivered'],['BM-2026-0511','Face shields × 6,000','Medisure Wholesale','UGX 40,800,000','06 Aug 2026','In transit'],['BM-2026-0478','Medical scrubs × 900 sets','Medisure Wholesale','UGX 55,800,000','27 Jul 2026','Delivered'],['BM-2026-0442','Surgical masks × 2,500 boxes','Medisure Wholesale','UGX 31,000,000','15 Jul 2026','Delivered']] },

  { role:'Buyer', id:'788 314 076', pass:'concrete2026', first:'Irene', person:'Irene Amongi', roleTitle:'Project procurement manager',
    initials:'SH', company:'Seeta Housing Developments Limited', trade:'Seeta Housing', meta:'Buyer · TIN 1008117433',
    email:'irene@seetahousing.co.ug', alt:'+256 701 664 219', addr:'Plot 88, Seeta Bypass, Mukono', district:'Mukono',
    tin:'1008117433', ursb:'80020010044612', licence:'MMC/TL/2026/00733', type:'Property developer', since:'June 2021',
    cats:['Building & construction','Packaging'],
    buys:'Ready-mix concrete, aggregates, blocks, formwork, cement',
    spend:'UGX 3.06bn', suppliers:'14',
    orders:[['BM-2026-0522','Ready-mix concrete C25 × 640 m³','Namanve Construction Supplies','UGX 297,600,000','13 Aug 2026','Delivered'],['BM-2026-0498','Aggregate 3/4 inch × 900 tonnes','Namanve Construction Supplies','UGX 70,200,000','05 Aug 2026','Delivered'],['BM-2026-0463','Solid blocks 9 inch × 24,000','Namanve Construction Supplies','UGX 103,200,000','23 Jul 2026','In transit'],['BM-2026-0430','Tororo cement 32.5N × 1,800 bags','Kampala Hardware Depot','UGX 59,040,000','12 Jul 2026','Delivered']] },

  { role:'Buyer', id:'701 447 320', pass:'agro2026', first:'Aisha', person:'Aisha Namutebi', roleTitle:'Head of sourcing',
    initials:'MF', company:'Mukwano Foods Processing Limited', trade:'Mukwano Foods', meta:'Buyer · TIN 1005512088',
    email:'aisha@mukwanofoods.co.ug', alt:'+256 772 884 110', addr:'Plot 30, Seventh Street, Industrial Area', district:'Kampala',
    tin:'1005512088', ursb:'80020009912440', licence:'KCCA/TL/2026/22190', type:'Food processor', since:'August 2022',
    cats:['Agriculture','Packaging'],
    buys:'Maize grain, sunflower seed, cartons, woven bags',
    spend:'UGX 1.42bn', suppliers:'23',
    orders:[['BM-2026-0501','White maize grain × 240 tonnes','Nile Grain and Produce','UGX 348,000,000','11 Aug 2026','Delivered'],['BM-2026-0466','Sunflower oil 20L × 900','Lira Oil Millers','UGX 124,200,000','29 Jul 2026','Delivered'],['BM-2026-0412','Woven bags 100kg × 40,000','Nile Packaging Works','UGX 50,000,000','16 Jul 2026','In transit'],['BM-2026-0388','Groundnuts × 18 tonnes','Masindi Grain Union','UGX 115,200,000','02 Jul 2026','Delivered']] },

  { role:'Buyer', id:'759 220 618', pass:'works2026', first:'Julius', person:'Julius Tumwine', roleTitle:'Workshop manager',
    initials:'MW', company:'Mbarara Metal Works Limited', trade:'Mbarara Metal Works', meta:'Buyer · TIN 1006733914',
    email:'julius@mbararametal.co.ug', alt:'+256 707 226 903', addr:'Plot 6, Kakoba Industrial Road, Mbarara', district:'Mbarara',
    tin:'1006733914', ursb:'80020007730118', licence:'MMC/TL/2026/00457', type:'Fabricator', since:'February 2023',
    cats:['Hardware & tools','Building & construction'],
    buys:'Hollow section, welding rods, power tools, sheet metal',
    spend:'UGX 96m', suppliers:'9',
    orders:[['BM-2026-0489','Hollow section 50×50 × 400','Kisekka Tools and Hardware','UGX 31,200,000','08 Aug 2026','Delivered'],['BM-2026-0451','Impact drill 18V × 60','Kisekka Tools and Hardware','UGX 22,140,000','24 Jul 2026','Delivered'],['BM-2026-0402','Y10 steel bar × 200','Steel & Tube Uganda','UGX 8,800,000','09 Jul 2026','Delivered'],['BM-2026-0377','Angle grinder 900W × 24','Buildmart Tools UG','UGX 4,440,000','27 Jun 2026','Cancelled']] },

{ role:'Admin', id:'aisha.n@bubu.market', pass:'ops2026', first:'Aisha', person:'Aisha Nsubuga', roleTitle:'Verification lead',
    initials:'BA', company:'BUBU.Market Uganda Limited', trade:'Platform operations', meta:'Admin console',
    email:'aisha.n@bubu.market', alt:'+256 800 218 400', addr:'Level 4, Acacia Place, Kololo', district:'Kampala',
    tin:'1000000001', ursb:'80020000000001', licence:'KCCA/TL/2026/00001', type:'Marketplace operator', since:'02 January 2024',
    cats:['Medical supplies','Building & construction'] }
];

const IND_CONTACTS = (st) => ((INDUSTRY[st.acct] || INDUSTRY[0]).contacts);

const INDUSTRY = {
  0: { // Kampala Hardware Depot · building materials
    reco: [['Roofing sheets 30g','132 approved leads','x-roofing'],['Binding wire 16g','94 approved leads','x-wire'],['Y10 steel bar','86 approved leads','x-y10'],['Hollow section 50×50','65 approved leads','x-hollow'],['Wheelbarrow heavy duty','54 approved leads','x-wheelbarrow'],['Concrete nails 4in','41 approved leads','x-nails']],
    perf: [['Tororo Portland Cement 32.5N, 50kg','UGX 33,500 / bag','412','38','9 enquiries','2.2%',22,'Kampala','p1-cement'],['Deformed steel bar Y12, 12m','UGX 62,000 / bar','268','21','6 enquiries','2.2%',22,'Wakiso','p2-steelbar'],['Roofing sheets 30g','UGX 48,500 / sheet','196','24','7 enquiries','3.6%',36,'Mukono','x-roofing'],['Binding wire 16g','UGX 9,200 / kg','142','19','4 enquiries','2.8%',28,'Kampala','x-wire'],['Hollow section 50×50','UGX 78,000 / length','118','16','3 enquiries','2.5%',25,'Wakiso','x-hollow'],['Concrete nails 4in','UGX 8,400 / kg','92','14','2 enquiries','2.1%',21,'Jinja','x-nails']],
    contacts: [
      ['Nakawa Trading Co. Ltd','Grace Nakato','Ntinda, Kampala','+256 772 903 445','Call received, cement enquiry','Cement 32.5N, 500 bags','14 Aug', true, true, true],
      ['Seeta Housing Developments','Irene Amongi','Mukono','+256 788 314 076','Needs 1,800 bags before month end','Cement 32.5N, 1,800 bags','14 Aug', true, false, true],
      ['Kyanja Builders Ltd','Peter Ssemakula','Kyanja, Kampala','+256 752 118 340','Call attempted, incoming','Steel bar Y12, 80 bars','13 Aug', true, true, false],
      ['Mukono Works Ltd','Sarah Auma','Mukono','+256 701 664 219','Quote for roofing sheets before Friday','Roofing sheets 30g, 900 sheets','13 Aug', true, false, true],
      ['Mbarara Metal Works','Julius Tumwine','Mbarara','+256 759 220 618','Wants Y10 bar and hollow section','Y10 bar, 200 bars','11 Aug', false, false, true],
      ['Jinja Estates','Denis Okot','Jinja','+256 774 552 013','Thank you, the delivery arrived','Binding wire, 400 kg','09 Aug', false, false, false]],
    leadTitles: [['Tororo Portland Cement 32.5N, 50kg bag','Cement','500 bags','Nakawa Trading Co. Ltd','Ntinda, Kampala'],['Deformed steel bar Y12, 12m length','Steel bar','80 bars','Kyanja Builders Ltd','Kyanja, Kampala'],['Pre-painted roofing sheets 30 gauge','Roofing','900 sheets','Mukono Works Ltd','Mukono']] },
  1: { // Kisekka Tools · hardware and tools
    reco: [['Angle grinder 900W','118 approved leads','t-grinder'],['Drill bit set 19pc','96 approved leads','t-drillbits'],['Concrete nails 4in','74 approved leads','x-nails'],['Steel wheelbarrow','58 approved leads','x-wheelbarrow'],['Binding wire 16g','44 approved leads','x-wire'],['Solar inverter 3kVA','37 approved leads','p5-inverter']],
    perf: [['Cordless impact drill 18V','UGX 385,000 / unit','386','44','12 enquiries','3.1%',31,'Kampala','t-drill'],['Angle grinder 900W','UGX 185,000 / unit','264','31','8 enquiries','3.0%',30,'Wakiso','t-grinder'],['Drill bit set, 19 pieces','UGX 46,000 / set','188','27','5 enquiries','2.7%',27,'Kampala','t-drillbits'],['Steel wheelbarrow, heavy duty','UGX 168,000 / unit','154','22','4 enquiries','2.6%',26,'Mbarara','x-wheelbarrow'],['Concrete nails 4in','UGX 8,400 / kg','131','18','3 enquiries','2.3%',23,'Jinja','x-nails'],['Solar inverter 3kVA hybrid','UGX 1,250,000 / unit','88','12','2 enquiries','2.3%',23,'Kampala','p5-inverter']],
    contacts: [
      ['Mbarara Metal Works','Julius Tumwine','Mbarara','+256 759 220 618','Wants 60 impact drills with warranty','Impact drill 18V, 60 units','14 Aug', true, true, true],
      ['Kyanja Builders Ltd','Peter Ssemakula','Kyanja, Kampala','+256 752 118 340','Asked for grinder trade price','Angle grinder 900W, 24 units','14 Aug', true, true, false],
      ['Seeta Housing Developments','Irene Amongi','Mukono','+256 788 314 076','Needs formwork clamps and bits','Drill bit set, 40 sets','13 Aug', true, false, true],
      ['Gulu Technical Institute','Denis Okot','Gulu','+256 703 887 145','Tender for workshop tools','Tool kits, 30 sets','12 Aug', false, false, false],
      ['Jinja Fabricators','Sarah Auma','Jinja','+256 774 552 013','Repeat order on nails and wire','Concrete nails, 600 kg','10 Aug', false, false, true],
      ['Nakawa Trading Co. Ltd','Grace Nakato','Ntinda, Kampala','+256 772 903 445','Solar inverter for the site office','Inverter 3kVA, 2 units','08 Aug', true, false, true]],
    leadTitles: [['Cordless impact drill 18V with two batteries','Power tools','120 units','Mbarara Tools Centre','Mbarara'],['Angle grinder 900W, industrial duty','Power tools','24 units','Kyanja Builders Ltd','Kyanja, Kampala'],['Concrete nails 4 inch, galvanised','Fasteners','600 kg','Jinja Fabricators','Jinja']] },
  2: { // Nile Grain · agriculture
    reco: [['Sesame seed, hulled','128 approved leads','a-sesame-seed'],['Beans, yellow long','104 approved leads','a-beans-yellow'],['Groundnuts, red beauty','91 approved leads','a-groundnuts'],['Maize bran, animal feed','67 approved leads','a-maize-bran'],['Woven bags 100kg','52 approved leads','a-woven-bag'],['Robusta coffee, screen 15','48 approved leads','a-coffee-robusta']],
    perf: [['White maize grain, grade 1','UGX 1,450 / kg','442','52','14 enquiries','3.2%',32,'Lira','a-maize-grain'],['Refined sunflower oil, 20L jerrycan','UGX 138,000 / jerrycan','318','36','9 enquiries','2.8%',28,'Kampala','p4-oil'],['Sesame seed, hulled','UGX 5,900 / kg','244','29','7 enquiries','2.9%',29,'Gulu','a-sesame-hulled'],['Beans, yellow long','UGX 3,700 / kg','196','24','5 enquiries','2.6%',26,'Masindi','a-beans-yellow'],['Groundnuts, red beauty','UGX 6,400 / kg','162','21','4 enquiries','2.5%',25,'Lira','a-groundnuts'],['Robusta coffee, screen 15','UGX 9,800 / kg','128','19','4 enquiries','3.1%',31,'Kampala','a-coffee-robusta']],
    contacts: [
      ['Mukwano Foods Processing','Aisha Namutebi','Industrial Area, Kampala','+256 701 447 320','Confirming 240 tonnes for September','White maize, 240 tonnes','14 Aug', true, true, true],
      ['World Food Programme, Uganda','Grace Nakato','Kampala','+256 772 903 445','Aflatoxin certificates requested','Maize grain, 500 tonnes','14 Aug', true, true, true],
      ['Gulu Wholesale Foods','Denis Okot','Gulu','+256 703 887 145','Asked for sunflower oil pricing','Sunflower oil 20L, 300 jerrycans','13 Aug', true, false, false],
      ['Kigali Commodity Traders','Julius Tumwine','Kigali, Rwanda','+256 707 226 903','Export enquiry, sesame FOB Kampala','Sesame seed, 60 tonnes','12 Aug', false, false, true],
      ['Masindi Grain Union','Sarah Auma','Masindi','+256 774 552 013','Wants warehouse receipt terms','Beans, 80 tonnes','10 Aug', false, false, true],
      ['Lira Animal Feeds','Irene Amongi','Lira','+256 758 441 260','Weekly maize bran order','Maize bran, 20 tonnes','09 Aug', false, false, false]],
    leadTitles: [['White maize grain grade 1, 13.5% moisture','Cereals','240 tonnes','Mukwano Foods Processing','Industrial Area, Kampala'],['Refined sunflower oil, 20 litre jerrycan','Edible oils','300 jerrycans','Gulu Wholesale Foods','Gulu'],['Hulled sesame seed for export','Oilseeds','60 tonnes','Kigali Commodity Traders','Kigali, Rwanda']] },
  4: { // Medisure Wholesale · medical supplies
    reco: [['Face shield, isolation','118 approved leads','m-faceshield'],['Medical scrubs set','96 approved leads','m-scrubs'],['Surgical masks 3-ply','84 approved leads','p7-gloves'],['Examination gloves','77 approved leads','p7-gloves'],['Shipping cartons 5-ply','41 approved leads','p6-carton'],['Caustic soda flakes','33 approved leads','p9-caustic']],
    perf: [['Nitrile examination gloves, box of 100','UGX 41,000 / box','404','46','13 enquiries','3.2%',32,'Kampala','p7-gloves'],['Face shield, protective isolation','UGX 6,800 / unit','286','33','8 enquiries','2.8%',28,'Kampala','m-faceshield'],['Medical scrubs set, unisex','UGX 62,000 / set','232','28','7 enquiries','3.0%',30,'Mbarara','m-scrubs'],['Surgical masks 3-ply, box of 50','UGX 12,400 / box','188','24','5 enquiries','2.7%',27,'Gulu','p7-gloves'],['Corrugated shipping cartons, 5-ply','UGX 2,900 / carton','96','14','2 enquiries','2.1%',21,'Jinja','p6-carton'],['Caustic soda flakes, 25kg','UGX 195,000 / bag','74','11','2 enquiries','2.7%',27,'Kampala','p9-caustic']],
    contacts: [
      ['Nsambya Hospital Supplies','Peter Wasswa','Nsambya, Kampala','+256 752 664 209','Confirming 4,000 boxes for the quarter','Nitrile gloves, 4,000 boxes','14 Aug', true, true, true],
      ['Joint Medical Store','Grace Nakato','Nsambya, Kampala','+256 772 903 445','Framework tender, needs NDA release','Face shields, 6,000 units','14 Aug', true, true, true],
      ['Mbarara Regional Referral','Julius Tumwine','Mbarara','+256 759 220 618','Scrubs sizing chart requested','Scrubs, 900 sets','13 Aug', true, false, true],
      ['Gulu District Health Office','Denis Okot','Gulu','+256 774 552 013','Masks for the outreach programme','Masks, 2,500 boxes','11 Aug', false, false, false],
      ['Eastgate Medical Distributors','Aisha Namutebi','Nairobi, Kenya','+256 701 447 320','Export enquiry, EXW Kampala','Gloves, 4,000 boxes','10 Aug', false, false, true],
      ['Kampala Clinic Group','Irene Amongi','Ntinda, Kampala','+256 788 314 076','Monthly consumables order','Consumables, mixed','08 Aug', false, false, true]],
    leadTitles: [['Nitrile examination gloves, box of 100','Gloves','4,000 boxes','Nsambya Hospital Supplies','Nsambya, Kampala'],['Face shield, protective isolation','Protective equipment','6,000 units','Joint Medical Store','Nsambya, Kampala'],['Medical scrubs set, unisex','Workwear','900 sets','Mbarara Regional Referral','Mbarara']] },
  3: { // Namanve Construction
    reco: [['Solid block 9 inch','146 approved leads','c-block'],['Aggregate 3/4 inch','122 approved leads','c-aggregate'],['Lake sand, washed','98 approved leads','c-sand'],['Steel formwork panel','71 approved leads','c-formwork'],['Damp proof course','48 approved leads','c-dpc'],['Hardcore, quarry run','39 approved leads','c-hardcore']],
    perf: [['Ready-mix concrete C25','UGX 465,000 / m³','398','41','11 enquiries','2.8%',28,'Mukono','p1-cement'],['Aggregate 3/4 inch, crushed stone','UGX 78,000 / tonne','312','34','8 enquiries','2.6%',26,'Wakiso','c-aggregate'],['Solid concrete block 9 inch','UGX 4,300 / block','276','30','7 enquiries','2.5%',25,'Mukono','c-block'],['Lake sand, washed','UGX 62,000 / tonne','208','25','5 enquiries','2.4%',24,'Kampala','c-sand'],['Steel formwork panel, 1200×600','UGX 210,000 / panel','142','18','4 enquiries','2.8%',28,'Kampala','c-formwork'],['Hardcore, quarry run','UGX 48,000 / tonne','96','13','2 enquiries','2.1%',21,'Jinja','c-hardcore']],
    contacts: [
      ['Seeta Housing Developments','Irene Amongi','Mukono','+256 788 314 076','Pour scheduled for Thursday morning','Ready-mix C25, 640 m³','14 Aug', true, true, true],
      ['Nakawa Trading Co. Ltd','Grace Nakato','Ntinda, Kampala','+256 772 903 445','Aggregate for the slab','Aggregate 3/4, 900 tonnes','14 Aug', true, true, true],
      ['Kyanja Builders Ltd','Peter Ssemakula','Kyanja, Kampala','+256 752 118 340','Blocks for boundary wall','Solid blocks 9in, 24,000','13 Aug', true, false, true],
      ['UNRA Kampala Northern Bypass','Julius Tumwine','Kampala','+256 707 226 903','Framework enquiry for hardcore','Hardcore, 2,000 tonnes','12 Aug', false, false, false],
      ['Mukono District Works','Sarah Auma','Mukono','+256 701 664 219','Formwork hire and purchase','Formwork panels, 60','10 Aug', false, false, true],
      ['Jinja Estates','Denis Okot','Jinja','+256 774 552 013','Sand delivery confirmed','Lake sand, 120 tonnes','08 Aug', false, false, false]],
    leadTitles: [['Ready-mix concrete C25 for slab pour','Ready-mix','640 m³','Seeta Housing Developments','Mukono'],['Crushed stone aggregate 3/4 inch','Aggregates','900 tonnes','Nakawa Trading Co. Ltd','Ntinda, Kampala'],['Solid concrete blocks 9 inch','Blocks','24,000 blocks','Kyanja Builders Ltd','Kyanja, Kampala']] }
};

const DISTRICTS = [
  ['Kampala',0.3476,32.5825],['Wakiso',0.4044,32.4594],['Mukono',0.3533,32.7553],['Entebbe',0.0512,32.4637],
  ['Jinja',0.4244,33.2041],['Mbarara',-0.6072,30.6545],['Gulu',2.7724,32.2881],['Mbale',1.0827,34.1755],
  ['Masaka',-0.3410,31.7360],['Lira',2.2350,32.9097],['Fort Portal',0.6540,30.2750],['Arua',3.0201,30.9110],
  ['Hoima',1.4351,31.3524],['Soroti',1.7147,33.6111],['Kabale',-1.2410,29.9856],['Tororo',0.6928,34.1808]
];

const kmBetween = (a, b) => {
  const R = 6371, d = Math.PI / 180;
  const dLat = (b[1] - a[1]) * d, dLon = (b[2] - a[2]) * d;
  const x = Math.sin(dLat / 2) ** 2 + Math.cos(a[1] * d) * Math.cos(b[1] * d) * Math.sin(dLon / 2) ** 2;
  return Math.round(2 * R * Math.asin(Math.sqrt(x)));
};

const CONTACTS = [
  ['Nakawa Trading Co. Ltd','Grace Nakato','Ntinda, Kampala','+256 772 903 445','Call received on 0772 415 908, duration 57 sec','Cement 32.5N, 500 bags','14 Aug', true, true, true],
  ['Kyanja Builders Ltd','Peter Ssemakula','Kyanja, Kampala','+256 752 118 340','Call attempted, incoming','Steel bar Y12, 80 bars','14 Aug', true, false, true],
  ['Mukono Works Ltd','Irene Amongi','Mukono','+256 701 664 219','Hello, we need a quote for roofing sheets before Friday','Roofing sheets 30g, 900 sheets','13 Aug', true, true, false],
  ['Mbarara Tools Centre','Julius Tumwine','Mbarara','+256 707 226 903','Call received on 0752 118 340, duration 68 sec','Impact drill 18V, 120 units','13 Aug', true, false, true],
  ['Jinja Estates','Sarah Auma','Jinja','+256 774 552 013','Thank you, the delivery arrived in good order','Impact drill 18V, 40 units','11 Aug', false, false, true],
  ['Gulu Wholesale Foods','Denis Okot','Gulu','+256 703 887 145','Call attempted for cement, incoming','Cement 32.5N, 200 bags','09 Aug', false, false, false]
];

const ROLE_NAV = {
  Buyer: [['wHome','Marketplace','','⌂'],['wPost','Post requirement','','✎'],['wSearch','Search','','⌕'],['wOrders','Quotes','2','◫'],['wPlans','Payments','','⛁'],['wProfile','Profile','','◉'],['wRegister','Verification','2','✦']],
  Supplier: [['sdash','Dashboard','','⌂'],['sprofile','Company profile','','◉'],['sleads','Lead manager','3','✉'],['srfq','Buy leads','10','◈'],['scatalog','Products','42','▦'],['sorders','Orders','4','◫'],['spayouts','Invoices','','⛁'],['skyc','Photos & docs','','◍'],['ssettings','Settings','','⚙']],
  Admin: [['admin','Queue','$queue','⚑'],['aDisputes','Disputes','$disputes','⚖'],['aEscrow','Escrow','','⛁'],['aCats','Categories','','▦'],['aFees','Fee rules','','⚙'],['aUsers','Members','','◉']]
};
const SCREEN_ROLE = { wHome:'Buyer', wSearch:'Buyer', wProduct:'Buyer', wStore:'Buyer', wCart:'Buyer', wCheckout:'Buyer', wOrders:'Buyer', wRegister:'Buyer',
  wPost:'Buyer', wProfile:'Buyer', wPlans:'Buyer',
  sdash:'Supplier', sprofile:'Supplier', scatalog:'Supplier', srfq:'Supplier', squote:'Supplier', sorders:'Supplier', sstore:'Supplier', spayouts:'Supplier', skyc:'Supplier',  sleads:'Supplier', ssettings:'Supplier', admin:'Admin', aDisputes:'Admin', aEscrow:'Admin', aCats:'Admin', aFees:'Admin', aUsers:'Admin' };
const NAV_PARENT = { wProduct:'wSearch', wStore:'wSearch', wCart:'wCheckout', squote:'srfq' };


window.BUBU = { PRODUCTS, CATEGORIES, OFFERS, APPLICANTS, MODALS, NOTIF, PNS_FAQ, ACCOUNTS, IND_CONTACTS, INDUSTRY, DISTRICTS, kmBetween, CONTACTS, ROLE_NAV, SCREEN_ROLE, NAV_PARENT };
}